# Generated by Django 4.0.6 on 2022-10-15 12:48

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('Project_name', models.CharField(max_length=50)),
                ('project_images', models.FileField(default=None, max_length=250, upload_to='media')),
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_date', models.CharField(max_length=50)),
                ('project_heading', models.TextField()),
                ('project_half', models.TextField(default=None)),
                ('project_blogimage', models.FileField(default=None, max_length=250, upload_to='media')),
                ('project_content', tinymce.models.HTMLField()),
            ],
        ),
    ]
