# Generated by Django 4.0.6 on 2022-10-15 19:04

from django.db import migrations, models
import embed_video.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_project_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='hardware',
            fields=[
                ('Project_name', models.CharField(max_length=50)),
                ('project_images', models.FileField(default=None, max_length=250, upload_to='media')),
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_date', models.CharField(max_length=50)),
                ('project_heading', models.TextField()),
                ('project_half', models.TextField(default=None)),
                ('project_blogimage', models.FileField(default=None, max_length=250, upload_to='media')),
                ('project_content', tinymce.models.HTMLField()),
                ('project_video', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
